name: "backup fakeYoumo"

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  backup:
    name: back up FakeYoumo
    runs-on: ubuntu-22.04
    environment: backFakeYoumo
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "backup FakeYoumo"
        id: backup-fakeyoumo
        run: |
          sudo apt-get update
          sudo apt-get install python3
          sudo pip install praw
          python3 backup.py
        env:
          REDDIT_USER_NAME: ${{ secrets.REDDIT_USER_NAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BACKUP_SUBREDDIT_NAME: ${{ vars.BACKUP_SUBREDDIT_NAME}}
          
          
      - name: "Set up Git"
        run: |
          git config --global user.name "FakeYoumo"

      - name: "Commit changes"
        run: |
          git add .
          git commit -m "Backup Reddit posts"

      - name: "Push changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
          
