name: "backup fakeYoumo"

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  backup:
    name: back up FakeYoumo
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "backup FakeYoumo"
        id: backup-fakeyoumo
        run: |
          sudo apt-get update
          sudo apt-get install python3
          sudo pip install praw
          echo 'Hi ${{ env.BACKUP_SUBREDDIT_NAME }}'
          python3 backup.py
          
          
      - name: "Set up Git"
        run: |
          git config --global user.name "FakeYoumo"

      - name: "Commit changes"
        run: |
          git add .
          git commit -m "Backup Reddit posts"

      - name: "Push changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
          
